/**
 * AI NEET Coach — Custom Service Worker
 * 
 * Strategies:
 *   1. App Shell (NetworkFirst) — HTML pages load even offline from cache
 *   2. Static Assets (CacheFirst) — JS/CSS/images cached permanently
 *   3. API Data (StaleWhileRevalidate) — study plan, syllabus, blueprint served from cache while refreshing
 *   4. Background Sync — failed test submissions queued and retried when online
 * 
 * Generated by next-pwa, this file extends the default with custom runtime caching.
 */

// Default next-pwa precaching (auto-injected)
// This comment ensures next-pwa injects its precache manifest here

import { clientsClaim } from 'workbox-core';
import { ExpirationPlugin } from 'workbox-expiration';
import { CacheableResponsePlugin } from 'workbox-cacheable-response';
import { NetworkFirst, CacheFirst, StaleWhileRevalidate } from 'workbox-strategies';
import { registerRoute, NavigationRoute, Route } from 'workbox-routing';
import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching';
import { BackgroundSyncPlugin } from 'workbox-background-sync';

// Take control immediately
clientsClaim();

// Clean old caches
cleanupOutdatedCaches();

// Precache Next.js build output (auto-injected by next-pwa)
precacheAndRoute(self.__WB_MANIFEST || []);

// ──────────────────────────────────────────────
// 1. NAVIGATION — NetworkFirst with offline fallback
// ──────────────────────────────────────────────
registerRoute(
    ({ request }) => request.mode === 'navigate',
    new NetworkFirst({
        cacheName: 'pages-cache',
        networkTimeoutSeconds: 5,
        plugins: [
            new CacheableResponsePlugin({ statuses: [0, 200] }),
            new ExpirationPlugin({ maxEntries: 50, maxAgeSeconds: 24 * 60 * 60 }), // 1 day
        ],
    })
);

// ──────────────────────────────────────────────
// 2. STATIC ASSETS — CacheFirst (JS, CSS, fonts, images)
// ──────────────────────────────────────────────
registerRoute(
    ({ request }) =>
        request.destination === 'style' ||
        request.destination === 'script' ||
        request.destination === 'font',
    new CacheFirst({
        cacheName: 'static-assets',
        plugins: [
            new CacheableResponsePlugin({ statuses: [0, 200] }),
            new ExpirationPlugin({ maxEntries: 100, maxAgeSeconds: 30 * 24 * 60 * 60 }), // 30 days
        ],
    })
);

// Images
registerRoute(
    ({ request }) => request.destination === 'image',
    new CacheFirst({
        cacheName: 'image-cache',
        plugins: [
            new CacheableResponsePlugin({ statuses: [0, 200] }),
            new ExpirationPlugin({ maxEntries: 60, maxAgeSeconds: 7 * 24 * 60 * 60 }), // 7 days
        ],
    })
);

// ──────────────────────────────────────────────
// 3. API DATA — StaleWhileRevalidate for read-only APIs
//    Student sees cached data instantly, fresh data arrives in background
// ──────────────────────────────────────────────
const CACHEABLE_API_ROUTES = [
    '/api/study-plan',
    '/api/syllabus',
    '/api/blueprint',
    '/api/ncert/library',
    '/api/home/stats',
    '/api/auth/me',
    '/api/omr/tests',
];

registerRoute(
    ({ url }) => CACHEABLE_API_ROUTES.some(route => url.pathname.startsWith(route)),
    new StaleWhileRevalidate({
        cacheName: 'api-data-cache',
        plugins: [
            new CacheableResponsePlugin({ statuses: [0, 200] }),
            new ExpirationPlugin({ maxEntries: 30, maxAgeSeconds: 2 * 60 * 60 }), // 2 hours
        ],
    })
);

// ──────────────────────────────────────────────
// 4. BACKGROUND SYNC — Queue failed test submissions
//    If student loses network during test submit, retry when back online
// ──────────────────────────────────────────────
const testSubmitSync = new BackgroundSyncPlugin('test-submit-queue', {
    maxRetentionTime: 24 * 60, // Retry for up to 24 hours
    onSync: async ({ queue }) => {
        let entry;
        while ((entry = await queue.shiftRequest())) {
            try {
                await fetch(entry.request.clone());
            } catch (err) {
                await queue.unshiftRequest(entry);
                throw err;
            }
        }
    },
});

registerRoute(
    ({ url }) => url.pathname.startsWith('/api/tests/submit'),
    new NetworkFirst({
        cacheName: 'test-submit-cache',
        plugins: [testSubmitSync],
    }),
    'POST'
);

// Also queue OMR grading submissions
const omrGradeSync = new BackgroundSyncPlugin('omr-grade-queue', {
    maxRetentionTime: 24 * 60,
});

registerRoute(
    ({ url }) => url.pathname.startsWith('/api/omr/grade'),
    new NetworkFirst({
        cacheName: 'omr-grade-cache',
        plugins: [omrGradeSync],
    }),
    'POST'
);

// ──────────────────────────────────────────────
// 5. OFFLINE FALLBACK MESSAGE
// ──────────────────────────────────────────────
self.addEventListener('fetch', (event) => {
    if (event.request.mode === 'navigate') {
        event.respondWith(
            (async () => {
                try {
                    return await fetch(event.request);
                } catch (err) {
                    const cache = await caches.open('pages-cache');
                    const cachedResponse = await cache.match(event.request);
                    if (cachedResponse) return cachedResponse;

                    // Ultimate fallback — minimal offline page
                    return new Response(
                        `<!DOCTYPE html>
                        <html lang="en">
                        <head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
                        <title>Offline — AI NEET Coach</title>
                        <style>
                            body{font-family:system-ui,-apple-system,sans-serif;background:#0a0e1a;color:#e2e8f0;display:flex;align-items:center;justify-content:center;min-height:100vh;margin:0;text-align:center;padding:20px}
                            .box{max-width:400px}
                            h1{font-size:2rem;margin:0 0 12px}
                            p{color:#94a3b8;line-height:1.6}
                            .btn{display:inline-block;margin-top:20px;padding:12px 32px;background:#6366f1;color:#fff;border:none;border-radius:12px;font-size:1rem;font-weight:700;cursor:pointer;text-decoration:none}
                        </style></head>
                        <body><div class="box">
                            <div style="font-size:3rem;margin-bottom:16px">📡</div>
                            <h1>You're Offline</h1>
                            <p>Don't worry — your test progress is saved locally. As soon as you're back online, everything will sync automatically.</p>
                            <button class="btn" onclick="location.reload()">Try Again</button>
                        </div></body></html>`,
                        { headers: { 'Content-Type': 'text/html' } }
                    );
                }
            })()
        );
    }
});

// ──────────────────────────────────────────────
// 6. SKIP WAITING on message from client
// ──────────────────────────────────────────────
self.addEventListener('message', (event) => {
    if (event.data && event.data.type === 'SKIP_WAITING') {
        self.skipWaiting();
    }
});
